package com.example.ui

object Loc {
    private val en = mapOf(
        "appName" to "Naam Jap Tracker",
        "tabMantra" to "Mantra",
        "tabProfile" to "Profile",
        "tabHome" to "Home",
        "tabJournal" to "Journal",
        "tabSettings" to "Settings",
        "btnStartJap" to "Start Naam Jap",
        "achievements" to "Achievements",
        "widgetSimulator" to "Widget Simulator",
        "activeMantra" to "Selected Mantra",
        "levelTitle" to "Level",
        "nextLevel" to "Next Level in",
        "spiritualName" to "Spiritual Name",
        "spiritualBio" to "Spiritual Bio / Motto",
        "save" to "Save",
        "cancel" to "Cancel",
        "hapticFeedback" to "Haptic Feedback",
        "vibrateOnCounter" to "Vibrate on counter clicks",
        "soundFeedback" to "Sound Feedback",
        "clickBeeps" to "Click beeps & completed bell sound",
        "keepScreenAwake" to "Keep Screen Awake",
        "preventSleeping" to "Prevent device sleeping when counter is open",
        "visualThemes" to "Visual Themes",
        "selectLanguage" to "App Language / भाषा",
        "english" to "English",
        "hindi" to "Hindi (हिंदी)",
        "averageDaily" to "Average Daily",
        "bestDay" to "Best Day",
        "totalMala" to "Total Mala (108)",
        "totalDays" to "Total Days",
        "spiritualAnalytics" to "Spiritual Analytics",
        "dailyAchievements" to "Daily Achievements",
        "editSpiritualProfile" to "Edit Spiritual Profile",
        "chooseAvatar" to "Choose Your Avatar Symbol",
        "spiritualBioDefault" to "Spiritual traveler on the path of Naam Jap.",
        "addMantra" to "Add Mantra",
        "mantraName" to "Mantra Name",
        "dailyGoal" to "Daily Goal",
        "theme" to "Theme",
        "myMantras" to "My Mantras",
        "editMantra" to "Edit Mantra",
        "deleteMantra" to "Delete Mantra",
        "dailyGoalAchieved" to "Daily Goal Achieved!",
        "totalChants" to "Total Chants",
        "quickSelectMantra" to "Quick Chanting Counter",
        "vibrationAndSounds" to "Vibrations & Sounds",
        "settingsAndCustomization" to "Settings & Customization",
        "preferencesDesc" to "Preferences, achievements, and offline database utility.",
        "backupAndRestore" to "Backup & Local Recovery",
        "backupDesc" to "Export or import your offline progress data anytime.",
        "exportBackup" to "Export Backup JSON",
        "importBackup" to "Import Backup JSON",
        "copiedToClipboard" to "Copied to clipboard!",
        "pasteJsonHere" to "Paste exported backup JSON here...",
        "restoreData" to "Restore Data",
        "restoreSuccess" to "Database restored successfully!",
        "restoreError" to "Invalid JSON data structure.",
        "dangerZone" to "Danger Zone",
        "resetAll" to "Reset All App Data",
        "resetDesc" to "This will permanently delete all chants, journal, mantras and settings.",
        "yesReset" to "Yes, Reset Everything",
        "addJournalEntry" to "Add Spiritual Journal Entry",
        "journalTitle" to "Title",
        "journalNote" to "Write your spiritual realizations, thoughts, or experience...",
        "saveEntry" to "Save Entry",
        "noJournalEntries" to "Your spiritual journal is empty. Record your first realization today!",
        "spiritualJournal" to "Spiritual Journal",
        "journalDesc" to "Write down your experiences, focus levels, and thoughts during chanting.",
        "clickToCounter" to "Tap Here to Chant",
        "back" to "Back",
        "customStatusPlaceholder" to "e.g. Dedicated Seeker",
        "spiritualBioPlaceholder" to "Write your chanting motive...",
        "beginnerSeeker" to "Beginner Seeker",
        "congratulations" to "Congratulations!",
        "unlockedAchievement" to "You unlocked an achievement!",
        "dismiss" to "Dismiss",
        "newMantraCreated" to "New mantra created!",
        "close" to "Close",
        "achievementsTitle" to "Unlocked Achievements",
        "achievementsSub" to "Milestones reached on your spiritual path",
        "quickSelect" to "Select Mantra",
        "todayChants" to "Today's Progress",
        "target" to "Target",
        "addMantraDesc" to "Create a new chanting practice",
        "activeMantraCard" to "Active Chanting",
        "customStatusLabel" to "Custom Status/Title",
        "beginner" to "Beginner Seeker",
        "totalChantsProfile" to "Total Chanting Repetitions"
    )

    private val hi = mapOf(
        "appName" to "नाम जप ट्रैकर",
        "tabMantra" to "मंत्र",
        "tabProfile" to "प्रोफाइल",
        "tabHome" to "होम",
        "tabJournal" to "डायरी",
        "tabSettings" to "सेटिंग्स",
        "btnStartJap" to "नाम जप शुरू करें",
        "achievements" to "उपलब्धियां",
        "widgetSimulator" to "विजेट सिम्युलेटर",
        "activeMantra" to "चयनित मंत्र",
        "levelTitle" to "स्तर",
        "nextLevel" to "अगले स्तर के लिए",
        "spiritualName" to "आध्यात्मिक नाम",
        "spiritualBio" to "आध्यात्मिक परिचय",
        "save" to "सुरक्षित करें",
        "cancel" to "रद्द करें",
        "hapticFeedback" to "वाइब्रेशन फीडबैक",
        "vibrateOnCounter" to "काउंटर क्लिक पर वाइब्रेशन",
        "soundFeedback" to "ध्वनि फीडबैक",
        "clickBeeps" to "क्लिक आवाज़ और घंटी की ध्वनि",
        "keepScreenAwake" to "स्क्रीन चालू रखें",
        "preventSleeping" to "काउंटर खुला होने पर स्क्रीन बंद न होने दें",
        "visualThemes" to "थीम्स",
        "selectLanguage" to "ऐप की भाषा / Language",
        "english" to "अंग्रेजी (English)",
        "hindi" to "हिंदी",
        "averageDaily" to "दैनिक औसत",
        "bestDay" to "सर्वश्रेष्ठ दिन",
        "totalMala" to "कुल माला (108)",
        "totalDays" to "कुल दिन",
        "spiritualAnalytics" to "आध्यात्मिक विश्लेषण",
        "dailyAchievements" to "दैनिक उपलब्धियां",
        "editSpiritualProfile" to "आध्यात्मिक प्रोफाइल बदलें",
        "chooseAvatar" to "अपना अवतार चिह्न चुनें",
        "spiritualBioDefault" to "नाम जप के मार्ग पर एक आध्यात्मिक यात्री।",
        "addMantra" to "मंत्र जोड़ें",
        "mantraName" to "मंत्र का नाम",
        "dailyGoal" to "दैनिक लक्ष्य",
        "theme" to "थीम",
        "myMantras" to "मेरे मंत्र",
        "editMantra" to "मंत्र संपादित करें",
        "deleteMantra" to "मंत्र हटाएं",
        "dailyGoalAchieved" to "दैनिक लक्ष्य प्राप्त हुआ!",
        "totalChants" to "कुल जप",
        "quickSelectMantra" to "त्वरित जप काउंटर",
        "vibrationAndSounds" to "वाइब्रेशन और ध्वनि",
        "settingsAndCustomization" to "सेटिंग्स और कस्टमाइज़ेशन",
        "preferencesDesc" to "प्राथमिकताएं, उपलब्धियां और ऑफलाइन डेटाबेस प्रणालियां।",
        "backupAndRestore" to "बैकअप और स्थानीय पुनर्प्राप्ति",
        "backupDesc" to "अपने ऑफलाइन डेटा को कभी भी निर्यात या आयात करें।",
        "exportBackup" to "बैकअप निर्यात करें (JSON)",
        "importBackup" to "बैकअप आयात करें (JSON)",
        "copiedToClipboard" to "क्लिपबोर्ड पर कॉपी किया गया!",
        "pasteJsonHere" to "यहां निर्यात किया गया बैकअप JSON पेस्ट करें...",
        "restoreData" to "डेटा पुनर्स्थापित करें",
        "restoreSuccess" to "डेटाबेस सफलतापूर्वक पुनर्स्थापित किया गया!",
        "restoreError" to "अमान्य JSON डेटा संरचना।",
        "dangerZone" to "खतरे का क्षेत्र",
        "resetAll" to "सभी ऐप डेटा रीसेट करें",
        "resetDesc" to "यह स्थायी रूप से सभी जप, डायरी, मंत्र और सेटिंग्स को हटा देगा।",
        "yesReset" to "हां, सब कुछ रीसेट करें",
        "addJournalEntry" to "आध्यात्मिक डायरी प्रविष्टि जोड़ें",
        "journalTitle" to "शीर्षक",
        "journalNote" to "अपने आध्यात्मिक अनुभव, विचार या अनुभूति लिखें...",
        "saveEntry" to "प्रविष्टि सहेजें",
        "noJournalEntries" to "आपकी आध्यात्मिक डायरी खाली है। आज अपना पहला आध्यात्मिक अनुभव लिखें!",
        "spiritualJournal" to "आध्यात्मिक डायरी",
        "journalDesc" to "जप के दौरान अपने अनुभव, ध्यान के स्तर और विचार लिखें।",
        "clickToCounter" to "जप करने के लिए यहां दबाएं",
        "back" to "वापस",
        "customStatusPlaceholder" to "जैसे: समर्पित साधक",
        "spiritualBioPlaceholder" to "अपना जप उद्देश्य लिखें...",
        "beginnerSeeker" to "शुरुआती साधक",
        "congratulations" to "बधाई हो!",
        "unlockedAchievement" to "आपने एक उपलब्धि हासिल की!",
        "dismiss" to "बंद करें",
        "newMantraCreated" to "नया मंत्र बनाया गया!",
        "close" to "बंद करें",
        "achievementsTitle" to "अनलॉक की गई उपलब्धियां",
        "achievementsSub" to "आपके आध्यात्मिक पथ पर महत्वपूर्ण पड़ाव",
        "quickSelect" to "मंत्र चुनें",
        "todayChants" to "आज की प्रगति",
        "target" to "लक्ष्य",
        "addMantraDesc" to "नया मंत्र अभ्यास शुरू करें",
        "activeMantraCard" to "सक्रिय मंत्र जप",
        "customStatusLabel" to "कस्टम स्थिति / शीर्षक",
        "beginner" to "शुरुआती साधक",
        "totalChantsProfile" to "कुल मंत्र जप आवृत्ति"
    )

    fun get(key: String, language: String): String {
        val map = if (language.equals("Hindi", ignoreCase = true)) hi else en
        return map[key] ?: en[key] ?: key
    }
}
